// <auto-generated />
namespace SASF.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCampoNovo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCampoNovo));
        
        string IMigrationMetadata.Id
        {
            get { return "201805080217450_AddCampoNovo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
